---
## os-controller
network:
  ethernets:
    #os internal network
    ens18:
      addresses:
      - 10.79.0.10/24
      gateway4: 10.79.0.1
      nameservers:
        addresses:
        - 10.79.0.1
      mtu: 1500
    #os providers network
    ens19:
      mtu: 1500
    #ceph public network
    ens20:
      addresses:
      - 10.96.0.10/24
      mtu: 9000
  version: 2
---
## os-compute01
network:
  ethernets:
    #os internal network
    ens18:
      addresses:
      - 10.79.0.11/24
      gateway4: 10.79.0.1
      nameservers:
        addresses:
        - 10.79.0.1
      mtu: 1500
    #os providers network
    ens19:
      mtu: 1500
    #ceph public network
    ens20:
      addresses:
      - 10.96.0.11/24
      mtu: 9000
  version: 2
  vlans:
    #ceph cluster network
    vlan69:
      addresses:
      - 10.69.0.11/24
      id: 69
      link: ens20
      mtu: 9000
---
## os-compute02
network:
  ethernets:
    #os internal network
    ens18:
      addresses:
      - 10.79.0.12/24
      gateway4: 10.79.0.1
      nameservers:
        addresses:
        - 10.79.0.1
      mtu: 1500
    #os providers network
    ens19:
      mtu: 1500
    #ceph public network
    ens20:
      addresses:
      - 10.96.0.12/24
      mtu: 9000
  version: 2
  vlans:
    #ceph cluster network
    vlan69:
      addresses:
      - 10.69.0.12/24
      id: 69
      link: ens20
      mtu: 9000
---